services:
  prometheus:
    image: prom/prometheus:v2.55.1
    container_name: mon_prometheus
    command: ["--config.file=/etc/prometheus/prometheus.yml", "--storage.tsdb.retention.time=15d"]
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks: [mon_net]

  alertmanager:
    image: prom/alertmanager:v0.27.0
    container_name: mon_alertmanager
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    ports:
      - "9093:9093"
    networks: [mon_net]

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: mon_cadvisor
    ports:
      - "8081:8080"   # 8080 déjà pris par Airflow -> expose 8081
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks: [mon_net]

  blackbox:
    image: prom/blackbox-exporter:v0.25.0
    container_name: mon_blackbox
    ports:
      - "9115:9115"
    volumes:
      - ./blackbox.yml:/etc/blackbox_exporter/config.yml:ro
    networks: [mon_net]

  grafana:
    image: grafana/grafana:11.2.0
    container_name: mon_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    networks: [mon_net]

networks:
  mon_net:
    name: mon_net
